]language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - cd core && pipenv run nose2 -s arxiv/ --with-coverage && coveralls && cd ..
after_success:
  - tests/lint.sh
  - tests/docstyle.sh
