language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
  - pipenv run nose2 --with-coverage
  - PYLINT_SCORE=$( pipenv run pylint core/events metadata/metadata | tail -2 | grep -Eo '[0-9\.]+/10' | tail -1 | sed s/\\/10// );
    PYLINT_PASS=$(echo $PYLINT_SCORE">="$MIN_PYLINT_SCORE | bc -l);
    if [ "$TRAVIS_PULL_REQUEST_SHA" = "" ];  then SHA=$TRAVIS_COMMIT; else SHA=$TRAVIS_PULL_REQUEST_SHA; fi;
    if [ "$PYLINT_PASS" ]; then PYLINT_STATE="success" &&  echo "pylint passed with score "$PYLINT_SCORE" for sha "$SHA; else PYLINT_STATE="failure" &&  echo "pylint failed with score "$PYLINT_SCORE" for sha "$SHA; fi
after_success:
  - coveralls
