language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install ./core --skip-lock
  - pipenv run nose2 -s core/arxiv --with-coverage
after_success:
  - coveralls
#  - tests/lint.sh
  - tests/docstyle.sh
