language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install ./core --skip-lock
  - pipenv run pytest --cov=agent --cov=core/arxiv --cov-report=term-missing agent core/arxiv
after_success:
  - coveralls
#  - tests/lint.sh
  - tests/docstyle.sh
