version: '3'

services:
  submission-maria:
    image: mariadb:10.3
    container_name: submission-maria
    networks:
      - arxiv-submission-local
    environment:
      MYSQL_USER: foouser
      MYSQL_PASSWORD: foopass
      MYSQL_ROOT_PASSWORD: foorootpassword
      MYSQL_DATABASE: submission
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3307:3306"

  submission-redis:
    image: redis
    container_name: submission-redis
    networks:
      - arxiv-submission-local

  # submission-localstack:
  #   image: atlassianlabs/localstack
  #   container_name: submission-localstack
  #   networks:
  #     - arxiv-submission-local
  #   ports:
  #     - "4568:4568"
  #     - "4569:4569"
  #   environment:
  #     USE_SSL: 'true'
  #     DEBUG: 'true'

  submission-metadata:
    build:
      context: ./
      dockerfile: Dockerfile-metadata
    container_name: submission-metadata
    environment:
      REDIS_ENDPOINT: "submission-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      LOGLEVEL: 10
      CLASSIC_DATABASE_URI: "mysql+mysqldb://foouser:foopass@submission-maria:3306/submission?charset=utf8"
    networks:
      - arxiv-submission-local
    depends_on:
      - submission-redis
      - submission-maria
      # - submission-localstack


  submission-authorization:
    build:
      context: ./authorization/
      dockerfile: Dockerfile
    container_name: submission-authorization
    environment:
      LOGLEVEL: 10
    networks:
      - arxiv-submission-local

  submission-gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    container_name: submission-gateway
    environment:
      REDIS_ENDPOINT: "submission-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      LOGLEVEL: 10
    ports:
      - "8000:8000"
    networks:
      - arxiv-submission-local
    depends_on:
      - submission-redis
      - submission-metadata
      - submission-authorization
      # - submission-localstack

networks:
  arxiv-submission-local:
