version: '3'

services:
  submission-maria:
    image: mariadb:10.3
    container_name: submission-maria
    networks:
      - arxiv-submission-local
    environment:
      MYSQL_USER: foouser
      MYSQL_PASSWORD: foopass
      MYSQL_ROOT_PASSWORD: foorootpassword
      MYSQL_DATABASE: submission
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3307:3306"

  submission-redis:
    image: redis
    container_name: submission-redis
    networks:
      - arxiv-submission-local

  submission-metadata:
    build:
      context: ./
      dockerfile: Dockerfile-metadata
    container_name: submission-metadata
    environment:
      REDIS_ENDPOINT: "submission-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      LOGLEVEL: 10
      CLASSIC_DATABASE_URI: "mysql+mysqldb://foouser:foopass@submission-maria:3306/submission?charset=utf8"
      JWT_SECRET: foosecret
    networks:
      - arxiv-submission-local
    depends_on:
      - submission-redis
      - submission-maria
      # - submission-localstack

  submission-authorization:
    image: arxiv/authenticator:0.1
    container_name: submission-auth
    environment:
      LOGLEVEL: 10
      REDIS_HOST: "submission-redis"
      REDIS_PORT: "6379"
      JWT_SECRET: foosecret
    networks:
      - arxiv-submission-local

  submission-registry-maria:
    image: mariadb:10.3
    container_name: submission-registry-maria
    networks:
      - arxiv-submission-local
    environment:
      MYSQL_USER: foouser
      MYSQL_PASSWORD: foopass
      MYSQL_ROOT_PASSWORD: foorootpassword
      MYSQL_DATABASE: clients
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3308:3306"

  submission-registry:
    image: arxiv/registry:0.1
    container_name: submission-registry
    environment:
      REDIS_HOST: "submission-redis"
      REDIS_PORT: "6379"
      LOGLEVEL: 10
      REGISTRY_DATABASE_URI: "mysql+mysqldb://foouser:foopass@submission-registry-maria:3306/clients?charset=utf8"
      AUTHLIB_INSECURE_TRANSPORT: "true"
      JWT_SECRET: foosecret
    depends_on:
      - submission-registry-maria
    networks:
      - arxiv-submission-local

  submission-gateway:
    build:
      context: ./gateway/
      dockerfile: Dockerfile
    container_name: submission-gateway
    environment:
      REDIS_ENDPOINT: "submission-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      LOGLEVEL: 10
    ports:
      - "8000:8000"
    networks:
      - arxiv-submission-local
    depends_on:
      - submission-redis
      - submission-metadata
      - submission-authorization
      - submission-registry

networks:
  arxiv-submission-local:
