openapi: "3.0.0"
info:
  version: "0.1"
  title: "arXiv Submission Events API"
  description: |
    The submission events service is the primary point of control for all
    data-transforming events in the submission system.
  contact:
    name: "arXiv API Team"
    email: nextgen@arxiv.org
  license:
    name: MIT
components:
  responses:
    NotFound:
      description: Resource not found.
    BadRequest:
      description: Event data not valid.
    Unauthorized:
      description: Not authorized.
paths:
  /:
    get:
      operationId: getServiceStatus
      description: |
        Get information about the status of the submission event service.
      responses:
        '200':
            description: Status of the submission event service.
  /create_submission/:
    post:
      operationId: createSubmission
      description: Create a new submission.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: 'resources/event.json'
                - $ref: 'resources/events/create_submission.json'
      responses:
        '201':
          description: Event was registered successfully.
          headers:
            Location:
              description: Location of the newly created event resource.
              schema:
                type: "string"
        '400':
          $ref: "#/components/responses/BadRequest"
        '403':
          $ref: "#/components/responses/Unauthorized"
  /submission/{submission_id}/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSubmissionState
      description: Get the current state of the submission.
      responses:
        '200':
          description: Returns submission details.
          content:
            application/json:
              schema:
                $ref: 'resources/submission.json'
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/events/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSubmissionEvents
      description: Retrieve the event log for this submission.
      responses:
        '200':
          description: Returns event details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'resources/event.json'
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/update_metadata/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: updateMetadata
      description: Update metadata fields on a submission.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: 'resources/event.json'
                - $ref: 'resources/events/update_metadata.json'
      responses:
        '201':
          description: Event was registered successfully.
          headers:
            Location:
              description: Location of the newly created event resource.
              schema:
                type: "string"
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/update_authors/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: updateAuthors
      description: Update authors on a submission.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: 'resources/event.json'
                - $ref: 'resources/events/update_authors.json'
      responses:
        '201':
          description: Event was registered successfully.
          headers:
            Location:
              description: Location of the newly created event resource.
              schema:
                type: "string"
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/add_license/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: selectLicense
      description: Select a license for the submission.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: 'resources/event.json'
                - $ref: 'resources/events/select_license.json'
      responses:
        '201':
          description: Event was registered successfully.
          headers:
            Location:
              description: Location of the newly created event resource.
              schema:
                type: "string"
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/events/{event_id}/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
      - name: event_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSubmissionEvent
      description: Identical to ``getEvent``.
      responses:
        '200':
          description: Returns event details.
          content:
            application/json:
              schema:
                $ref: 'resources/event.json'
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
  /submission/{submission_id}/events/{event_id}/state/:
    parameters:
      - name: submission_id
        in: path
        required: true
        schema:
          type: string
      - name: event_id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSubmissionStateAtEvent
      responses:
        '200':
          description: Returns submission details.
          content:
            application/json:
              schema:
                $ref: 'resources/submission.json'
        '403':
          $ref: "#/components/responses/Unauthorized"
        '404':
          $ref: "#/components/responses/NotFound"
